env:
    GH_USN: "ENCRYPTED[180983afb8112b462a1c9a5fe32fe90f1cf93481f94cb6594d73e2dc78ae0e7ba83b69d57d664b8c61416bc6b8eb12e5]"
    GH_EMAIL: "ENCRYPTED[b3d6c362a3f908f1f41f2c9910758b9029a0af1951f6992e190c6dba07f276d5d3f14202ceeddf90f5dbbbde8bc96398]"
    GH_CRED: "ENCRYPTED[4c1c14481e47322d661f9e5314cb099a875e2331a10f3e472836a93163bb4802e58116d46879883d479c8fff8325c2f2]"

task:
  name: "Android Build"
  timeout_in: 480m
  container:
      image: linear21/ubuntu:22
      cpu: 8
      memory: 32G

  rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - curl -so ~/.config/rclone/rclone.conf https://$GH_CRED@raw.githubusercontent.com/linear21/misc/master/rclone.conf

  git_setup_script:
      - git config --global user.name "$GH_USN"
      - git config --global user.email "$GH_EMAIL"
      - echo "https://$GH_USN:$GH_CRED@github.com" > ~/.git-credentials
      - git config --global credential.helper "store --file ~/.git-credentials"

  ccache_stats_script:
      - ccache -s

  build_start_script:
      - bash build.sh
